config/routes.rb
Rails.application.routes.draw do

  resources :misc_item_lines

  resources :accessory_lines

  resources :bid_sheets

  resources :concrete_slabs

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :customers

  resources :states

  resources :employees

end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
  has_many :accessory_lines
  has_many :bid_sheets, through: :accessory_lines
end

app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet
end

app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :transfer_switch
  belongs_to :concrete_slab
  belongs_to :generator
  has_many :misc_item_lines
  has_many :accessory_lines
  has_many :accessories, through: :accessory_lines



  validates :jobNumber, uniqueness: { scope: :jobNumber,
                                      message: "%{value} has already been used." }

end

app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets

  def set_cusfullname
    cusfullname = firstName + ' ' + lastName
    return cusfullname
  end

  def set_cusaddress
    cusaddress = streetAddress + ' ' + streetAddress2 + ', ' + city + ', ' + state.abbreviation + '  ' + zipCode.to_s
    return cusaddress
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets

  def set_empfullname
    empfullname = firstName + ' ' + lastName
    return empfullname
  end
end

app/models/generator.rb
class Generator < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/misc_item_line.rb
class MiscItemLine < ActiveRecord::Base
  belongs_to :bid_sheet
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :customers
end

app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  has_many :bid_sheets
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstName, :lastName, :streetAddress, :streetAddress2, :city, :state_id, :zipCode, :phone, :phone2, :email)
    end
end

app/controllers/generators_controller.rb
class GeneratorsController < ApplicationController
  before_action :set_generator, only: [:show, :edit, :update, :destroy]

  # GET /generators
  # GET /generators.json
  def index
    @generators = Generator.all
  end

  # GET /generators/1
  # GET /generators/1.json
  def show
  end

  # GET /generators/new
  def new
    @generator = Generator.new
  end

  # GET /generators/1/edit
  def edit
  end

  # POST /generators
  # POST /generators.json
  def create
    @generator = Generator.new(generator_params)

    respond_to do |format|
      if @generator.save
        format.html { redirect_to @generator, notice: 'Generator was successfully created.' }
        format.json { render :show, status: :created, location: @generator }
      else
        format.html { render :new }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generators/1
  # PATCH/PUT /generators/1.json
  def update
    respond_to do |format|
      if @generator.update(generator_params)
        format.html { redirect_to @generator, notice: 'Generator was successfully updated.' }
        format.json { render :show, status: :ok, location: @generator }
      else
        format.html { render :edit }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generators/1
  # DELETE /generators/1.json
  def destroy
    @generator.destroy
    respond_to do |format|
      format.html { redirect_to generators_url, notice: 'Generator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generator
      @generator = Generator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generator_params
      params.require(:generator).permit(:productDescription, :modelNumber, :phVolt, :dealer, :msrp, :map, :voltage, :mountedBreaker, :alternator, :activeStatus)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abbreviation)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/accessory_lines_helper.rb
module AccessoryLinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bid_sheets_helper.rb
module BidSheetsHelper
end

app/helpers/concrete_slabs_helper.rb
module ConcreteSlabsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/generators_helper.rb
module GeneratorsHelper
end

app/helpers/misc_item_lines_helper.rb
module MiscItemLinesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/generators/_form.html.erb
<%= form_for(@generator) do |f| %>
  <% if @generator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generator.errors.count, "error") %> prohibited this generator from being saved:</h2>

      <ul>
      <% @generator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Description" %><br>
    <%= f.text_area :productDescription %>
  </div>
  <div class="field">
    <%= f.label :"Model #" %><br>
    <%= f.text_field :modelNumber %>
  </div>
  <div class="field">
    <%= f.label :dealer %><br>
    $<%= f.text_field :dealer %>
  </div>
  <div class="field">
    <%= f.label :msrp %><br>
    $<%= f.text_field :msrp %>
  </div>
  <div class="field">
    <%= f.label :map %><br>
    $<%= f.text_field :map %>
  </div>
    <div class="field">
    <%= f.label :"PH Volt" %><br>
    <%= f.text_field :phVolt %>
  </div>
  <div class="field">
    <%= f.label :voltage %><br>
    $<%= f.text_field :voltage %>
  </div>
  <div class="field">
    <%= f.label :"Mounted Breaker" %><br>
    <%= f.text_field :mountedBreaker %>
  </div>
  <div class="field">
    <%= f.label :"Alternator" %><br>
    <%= f.text_field :alternator %>
  </div>
  <div class="field">
    <%= f.label :"Active" %><br>
    <%= f.check_box :activeStatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generators/edit.html.erb
<h1>Editing generator</h1>

<%= render 'form' %>

<%= link_to 'Back', generators_path %>

app/views/generators/index.html.erb
<h1>Listing Generators</h1>

<table class="center">
  <thead>
    <tr>
      <th>Description</th>
      <th>Model #</th>
      <th>PHVolt</th>
      <th>Dealer</th>
      <th>MSRP</th>
      <th>MAP</th>
      <th>Voltage</th>
      <th>Mounted Breaker</th>
      <th>Alternator</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generators.each do |generator| %>
      <tr>
        <td><%= generator.productDescription %></td>
        <td><%= generator.modelNumber %></td>
        <td><%= generator.phVolt %></td>
        <td><%= number_to_currency(generator.dealer) %></td>
        <td><%= number_to_currency(generator.msrp) %></td>
        <td><%= number_to_currency(generator.map) %></td>
        <td><%= generator.voltage %></td>
        <td><%= generator.mountedBreaker %></td>
        <td><%= generator.alternator %></td>
        <td><%= generator.activeStatus %></td>
        <td><%= link_to 'Edit', edit_generator_path(generator) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generator', new_generator_path %>

app/views/generators/new.html.erb
<h1>New generator</h1>

<%= render 'form' %>

<%= link_to 'Back', generators_path %>

app/views/generators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @generator.productDescription %>
</p>

<p>
  <strong>Model #:</strong>
  <%= @generator.modelNumber %>
</p>

<p>
  <strong>PH Volt:</strong>
  <%= @generator.phVolt %>
</p>

<p>
  <strong>Dealer:</strong>
  <%= number_to_currency(@generator.dealer) %>
</p>

<p>
  <strong>MSRP:</strong>
  <%= number_to_currency(@generator.msrp) %>
</p>

<p>
  <strong>MAP:</strong>
  <%= number_to_currency(@generator.map) %>
</p>

<p>
  <strong>Voltage:</strong>
  <%= @generator.voltage %>
</p>

<p>
  <strong>Mounted Breaker:</strong>
  <%= @generator.mountedBreaker %>
</p>

<p>
  <strong>Alternator:</strong>
  <%= @generator.alternator %>
</p>

<p>
  <strong>Active:</strong>
  <%= @generator.activeStatus %>
</p>

<%= link_to 'Edit', edit_generator_path(@generator) %> |
<%= link_to 'Back', generators_path %>