config/routes.rb
Rails.application.routes.draw do

  resources :misc_item_lines

  resources :accessory_lines

  resources :bid_sheets

  resources :concrete_slabs

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :customers

  resources :states

  resources :employees

end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
  has_many :accessory_lines
  has_many :bid_sheets, through: :accessory_lines
end

app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet
end

app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :transfer_switch
  belongs_to :concrete_slab
  belongs_to :generator
  has_many :misc_item_lines
  has_many :accessory_lines
  has_many :accessories, through: :accessory_lines



  validates :jobNumber, uniqueness: { scope: :jobNumber,
                                      message: "%{value} has already been used." }

end

app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets

  def set_cusfullname
    cusfullname = firstName + ' ' + lastName
    return cusfullname
  end

  def set_cusaddress
    cusaddress = streetAddress + ' ' + streetAddress2 + ', ' + city + ', ' + state.abbreviation + '  ' + zipCode.to_s
    return cusaddress
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets

  def set_empfullname
    empfullname = firstName + ' ' + lastName
    return empfullname
  end
end

app/models/generator.rb
class Generator < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/misc_item_line.rb
class MiscItemLine < ActiveRecord::Base
  belongs_to :bid_sheet
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :customers
end

app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  has_many :bid_sheets
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstName, :lastName, :streetAddress, :streetAddress2, :city, :state_id, :zipCode, :phone, :phone2, :email)
    end
end

app/controllers/misc_item_lines_controller.rb
class MiscItemLinesController < ApplicationController
  before_action :set_misc_item_line, only: [:show, :edit, :update, :destroy]

  # GET /misc_item_lines
  # GET /misc_item_lines.json
  def index
    @misc_item_lines = MiscItemLine.all
  end

  # GET /misc_item_lines/1
  # GET /misc_item_lines/1.json
  def show
  end

  # GET /misc_item_lines/new
  def new
    @misc_item_line = MiscItemLine.new
  end

  # GET /misc_item_lines/1/edit
  def edit
  end

  # POST /misc_item_lines
  # POST /misc_item_lines.json
  def create
    @misc_item_line = MiscItemLine.new(misc_item_line_params)

    respond_to do |format|
      if @misc_item_line.save
        format.html { redirect_to @misc_item_line, notice: 'Misc item line was successfully created.' }
        format.json { render :show, status: :created, location: @misc_item_line }
      else
        format.html { render :new }
        format.json { render json: @misc_item_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /misc_item_lines/1
  # PATCH/PUT /misc_item_lines/1.json
  def update
    respond_to do |format|
      if @misc_item_line.update(misc_item_line_params)
        format.html { redirect_to @misc_item_line, notice: 'Misc item line was successfully updated.' }
        format.json { render :show, status: :ok, location: @misc_item_line }
      else
        format.html { render :edit }
        format.json { render json: @misc_item_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /misc_item_lines/1
  # DELETE /misc_item_lines/1.json
  def destroy
    @misc_item_line.destroy
    respond_to do |format|
      format.html { redirect_to misc_item_lines_url, notice: 'Misc item line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_misc_item_line
      @misc_item_line = MiscItemLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def misc_item_line_params
      params.require(:misc_item_line).permit(:bidSheet_id, :itemName, :itemPrice)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abbreviation)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/accessory_lines_helper.rb
module AccessoryLinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bid_sheets_helper.rb
module BidSheetsHelper
end

app/helpers/concrete_slabs_helper.rb
module ConcreteSlabsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/generators_helper.rb
module GeneratorsHelper
end

app/helpers/misc_item_lines_helper.rb
module MiscItemLinesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/misc_item_lines/_form.html.erb
<%= form_for(@misc_item_line) do |f| %>
  <% if @misc_item_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@misc_item_line.errors.count, "error") %> prohibited this misc_item_line from being saved:</h2>

      <ul>
      <% @misc_item_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bidSheet_id %><br>
    <%= f.number_field :bidSheet_id %>
  </div>
  <div class="field">
    <%= f.label :itemName %><br>
    <%= f.text_field :itemName %>
  </div>
  <div class="field">
    <%= f.label :itemPrice %><br>
    <%= f.text_field :itemPrice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/misc_item_lines/edit.html.erb
<h1>Editing misc_item_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @misc_item_line %> |
<%= link_to 'Back', misc_item_lines_path %>

app/views/misc_item_lines/index.html.erb
<h1>Listing misc_item_lines</h1>

<table>
  <thead>
    <tr>
      <th>Bidsheet</th>
      <th>Itemname</th>
      <th>Itemprice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @misc_item_lines.each do |misc_item_line| %>
      <tr>
        <td><%= misc_item_line.bidSheet_id %></td>
        <td><%= misc_item_line.itemName %></td>
        <td><%= misc_item_line.itemPrice %></td>
        <td><%= link_to 'Show', misc_item_line %></td>
        <td><%= link_to 'Edit', edit_misc_item_line_path(misc_item_line) %></td>
        <td><%= link_to 'Destroy', misc_item_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Misc item line', new_misc_item_line_path %>

app/views/misc_item_lines/new.html.erb
<h1>New misc_item_line</h1>

<%= render 'form' %>

<%= link_to 'Back', misc_item_lines_path %>

app/views/misc_item_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bidsheet:</strong>
  <%= @misc_item_line.bidSheet_id %>
</p>

<p>
  <strong>Itemname:</strong>
  <%= @misc_item_line.itemName %>
</p>

<p>
  <strong>Itemprice:</strong>
  <%= @misc_item_line.itemPrice %>
</p>

<%= link_to 'Edit', edit_misc_item_line_path(@misc_item_line) %> |
<%= link_to 'Back', misc_item_lines_path %>