config/routes.rb
Rails.application.routes.draw do

  resources :misc_item_lines

  resources :accessory_lines

  resources :bid_sheets

  resources :concrete_slabs

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :customers

  resources :states

  resources :employees

end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
  has_many :accessory_lines
  has_many :bid_sheets, through: :accessory_lines
end

app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet
end

app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :transfer_switch
  belongs_to :concrete_slab
  belongs_to :generator
  has_many :misc_item_lines
  has_many :accessory_lines
  has_many :accessories, through: :accessory_lines



  validates :jobNumber, uniqueness: { scope: :jobNumber,
                                      message: "%{value} has already been used." }

end

app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets

  def set_cusfullname
    cusfullname = firstName + ' ' + lastName
    return cusfullname
  end

  def set_cusaddress
    cusaddress = streetAddress + ' ' + streetAddress2 + ', ' + city + ', ' + state.abbreviation + '  ' + zipCode.to_s
    return cusaddress
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets

  def set_empfullname
    empfullname = firstName + ' ' + lastName
    return empfullname
  end
end

app/models/generator.rb
class Generator < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/misc_item_line.rb
class MiscItemLine < ActiveRecord::Base
  belongs_to :bid_sheet
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :customers
end

app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  has_many :bid_sheets
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstName, :lastName, :streetAddress, :streetAddress2, :city, :state_id, :zipCode, :phone, :phone2, :email)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstName, :lastName)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abbreviation)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/accessory_lines_helper.rb
module AccessoryLinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bid_sheets_helper.rb
module BidSheetsHelper
end

app/helpers/concrete_slabs_helper.rb
module ConcreteSlabsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/generators_helper.rb
module GeneratorsHelper
end

app/helpers/misc_item_lines_helper.rb
module MiscItemLinesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :streetAddress %><br>
    <%= f.text_field :streetAddress %>
  </div>
  <div class="field">
    <%= f.label :streetAddress2 %><br>
    <%= f.text_field :streetAddress2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select(:state_id, State.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :zipCode %><br>
    <%= f.number_field :zipCode %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br>
    <%= f.number_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>ZIP Code</th>
      <th>Phone</th>
      <th>Phone 2</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.firstName %></td>
        <td><%= customer.lastName %></td>
        <td><%= customer.streetAddress %></td>
        <td><%= customer.streetAddress2 %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state.abbreviation %></td>
        <td><%= customer.zipCode %></td>
        <td><%= number_to_phone(customer.phone) %></td>
        <td><%= number_to_phone(customer.phone2) %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @customer.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @customer.lastName %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @customer.streetAddress %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @customer.streetAddress2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state.abbreviation %>
</p>

<p>
  <strong>ZIP:</strong>
  <%= @customer.zipCode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@customer.phone) %>
</p>

<p>
  <strong>Phone 2:</strong>
  <%= number_to_phone(@customer.phone2) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'First Name' %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :'Last Name' %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee <%= @employee.id %></h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.id %></td>
        <td><%= employee.firstName %></td>
        <td><%= employee.lastName %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastName %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= state.abbreviation %></td>
      </tr>
    <% end %>

  </tbody>

</table>
<br>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @state.abbreviation %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>