config/routes.rb
Rails.application.routes.draw do

  resources :misc_item_lines

  resources :accessory_lines

  resources :bid_sheets

  resources :concrete_slabs

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :customers

  resources :states

  resources :employees

end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
  has_many :accessory_lines
  has_many :bid_sheets, through: :accessory_lines
end

app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet
end

app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :transfer_switch
  belongs_to :concrete_slab
  belongs_to :generator
  has_many :misc_item_lines
  has_many :accessory_lines
  has_many :accessories, through: :accessory_lines



  validates :jobNumber, uniqueness: { scope: :jobNumber,
                                      message: "%{value} has already been used." }

end

app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets

  def set_cusfullname
    cusfullname = firstName + ' ' + lastName
    return cusfullname
  end

  def set_cusaddress
    cusaddress = streetAddress + ' ' + streetAddress2 + ', ' + city + ', ' + state.abbreviation + '  ' + zipCode.to_s
    return cusaddress
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets

  def set_empfullname
    empfullname = firstName + ' ' + lastName
    return empfullname
  end
end

app/models/generator.rb
class Generator < ActiveRecord::Base
  has_many :bid_sheets
end

app/models/misc_item_line.rb
class MiscItemLine < ActiveRecord::Base
  belongs_to :bid_sheet
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :customers
end

app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  has_many :bid_sheets
end

app/controllers/bid_sheets_controller.rb
class BidSheetsController < ApplicationController
  before_action :set_bid_sheet, only: [:show, :edit, :update, :destroy]

  # GET /bid_sheets
  # GET /bid_sheets.json
  def index
    @bid_sheets = BidSheet.all
  end



  # GET /bid_sheets/1
  # GET /bid_sheets/1.json
  def show
  end

  # GET /bid_sheets/new
  def new
    @bid_sheet = BidSheet.new
  end

  # GET /bid_sheets/1/edit
  def edit
  end

  # POST /bid_sheets
  # POST /bid_sheets.json
  def create
    @bid_sheet = BidSheet.new(bid_sheet_params)

    respond_to do |format|
      if @bid_sheet.save
        format.html { redirect_to @bid_sheet, notice: 'Bid sheet was successfully created.' }
        format.json { render :show, status: :created, location: @bid_sheet }
      else
        format.html { render :new }
        format.json { render json: @bid_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bid_sheets/1
  # PATCH/PUT /bid_sheets/1.json
  def update
    respond_to do |format|
      if @bid_sheet.update(bid_sheet_params)
        format.html { redirect_to @bid_sheet, notice: 'Bid sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid_sheet }
      else
        format.html { render :edit }
        format.json { render json: @bid_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bid_sheets/1
  # DELETE /bid_sheets/1.json
  def destroy
    @bid_sheet.destroy
    respond_to do |format|
      format.html { redirect_to bid_sheets_url, notice: 'Bid sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid_sheet
      @bid_sheet = BidSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_sheet_params
      params.require(:bid_sheet).permit(:employee_id, :customer_id, :jobNumber, :date, :generator_id, :transferswitch_id, :concreteslab_id, :laborCost, :laborTax, :genAtsTax, :markup, :taxExempt, :description, :completeStatus)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstName, :lastName, :streetAddress, :streetAddress2, :city, :state_id, :zipCode, :phone, :phone2, :email)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abbreviation)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/accessory_lines_helper.rb
module AccessoryLinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bid_sheets_helper.rb
module BidSheetsHelper
end

app/helpers/concrete_slabs_helper.rb
module ConcreteSlabsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/generators_helper.rb
module GeneratorsHelper
end

app/helpers/misc_item_lines_helper.rb
module MiscItemLinesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/bid_sheets/_form.html.erb
<%= form_for(@bid_sheet) do |f| %>
  <% if @bid_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid_sheet.errors.count, "error") %> prohibited this bid_sheet from being saved:</h2>

      <ul>
      <% @bid_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Employee %><br>
    <%= f.collection_select(:employee_id, Employee.all, :id, :set_empfullname) %>
  </div>
  <div class="field">
    <%= f.label :Customer %><br>
    <%= f.collection_select(:customer_id, Customer.all, :id, :set_cusfullname) %>
  </div>
  <div class="field">
    <%= f.label :'Job Number' %><br>
    <%= f.text_field :jobNumber %>
  </div>
  <div class="field">
    <%= f.label :Date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :Generator %><br>
    <%= f.collection_select(:generator_id, Generator.all, :id, :modelNumber) %>
  </div>
  <div class="field">
    <%= f.label :'Transfer Switch' %><br>
    <%= f.collection_select(:transferswitch_id, TransferSwitch.all, :id, :modelNumber) %>
  </div>
  <div class="field">
    <%= f.label :'Concrete Slab' %><br>
    <%= f.collection_select(:concreteslab_id, ConcreteSlab.all, :id, :slabName) %>
  </div>
  <div class="field">
    <%= f.label :'Labor Cost' %><br>
    $<%= f.text_field :laborCost %>
  </div>
  <div class="field">
    <%= f.label :'Labor Tax' %><br>
    <%= f.text_field :laborTax %>%
  </div>
  <div class="field">
    <%= f.label :'Gen/ATS Tax' %><br>
    <%= f.text_field :genAtsTax %>%
  </div>
  <div class="field">
    <%= f.label :Markup %><br>
    <%= f.text_field :markup %>%
  </div>
  <div class="field">
    <%= f.label :'Tax Exempt' %><br>
    <%= f.check_box :taxExempt %>
  </div>
  <div class="field">
    <%= f.label :'Job Description' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :'Complete' %><br>
    <%= f.check_box :completeStatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bid_sheets/edit.html.erb
<h1>Editing bid_sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid_sheet %> |
<%= link_to 'Back', bid_sheets_path %>

app/views/bid_sheets/index.html.erb
<h1>Listing Bid Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Customer</th>
      <th>Job #</th>
      <th>Date</th>
      <th>Labor Cost</th>
      <th>Generator</th>
      <th>Markup</th>
      <th>Tax Status</th>
      <th>Description</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bid_sheets.each do |bid_sheet| %>
      <tr>
        <td><%= bid_sheet.employee.set_empfullname %></td>
        <td><%= bid_sheet.customer.set_cusfullname %></td>
        <td><%= bid_sheet.jobNumber %></td>
        <td><%= bid_sheet.date %></td>
        <td><%= number_to_currency(bid_sheet.laborCost) %></td>
        <td><%= bid_sheet.generator.modelNumber %></td>
        <td><%= bid_sheet.markup %>%</td>
        <td><%= bid_sheet.taxExempt %></td>
        <td><%= bid_sheet.description %></td>
        <td><%= bid_sheet.completeStatus %></td>
        <td><%= link_to 'Show', bid_sheet %></td>
        <td><%= link_to 'Edit', edit_bid_sheet_path(bid_sheet) %></td>
        <td><%= link_to 'Destroy', bid_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid sheet', new_bid_sheet_path %>

app/views/bid_sheets/new.html.erb
<h1>New bid_sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', bid_sheets_path %>

app/views/bid_sheets/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset='UTF-8'>

  <title>Editable Invoice</title>

  <link rel='stylesheet' href='css/style.css'>
  <link rel='stylesheet' href='css/print.css' media="print">
  <script src='js/jquery-1.3.2.min.js'></script>
  <script src='js/example.js'></script>

</head>

<body>

<div id="page-wrap">

  <textarea id="header">INVOICE</textarea>

  <table>
    <tr>
  <div id="identity">
    <td>
    <p>
    <div id="logo">
      <%= image_tag("kiss.PNG", :alt => "logo") %>
    </div>
    </p>
    </td>

    <td>
    <p>
    <strong>Bill To:</strong></br></br>

    <%= @bid_sheet.customer.set_cusfullname %> </br>
    <%= @bid_sheet.customer.set_cusaddress %> </br>
    </p>
    </td>

  </div>
     </tr>
  </table>

  <div style="clear:both"></div>

  <div id="customer">

    <table id="meta">
      <tr>
        <td class="meta-head">Job #</td>
        <td><%= @bid_sheet.jobNumber %></td>
      </tr>
      <tr>

        <td class="meta-head">Date</td>
        <td><textarea id="date">Enter Date</textarea></td>
      </tr>
      <tr>
        <td class="meta-head">Total</td>
        <td><div class="due">$875.00</div></td>
      </tr>

    </table>

  </div>




    <div id="summary">
      <h5>Summary</h5>

<section>
      Kiss Generator Kohler <%= @bid_sheet.generator.productDescription %> <textarea cols="1" rows="1" style="font-size: 10px">Proposal</textarea></br>
      Thank you for asking KISS Generator Inc. to make a proposal for the standard power for your

         <select>
         <option value="home">home</option>
         <option value="business">business</option>
         </select>

      located at <%= @bid_sheet.customer.set_cusaddress %>.
      The pricing includes the installation of Kohler <%= @bid_sheet.generator.productDescription %>,<%= @bid_sheet.transferswitch_id %> transfer switch, [any other items checked on the bid sheet].</br>

      <% if @bid_sheet.customer.city == "Houston" %>
      <%= print "Any amendments requested by the City of Houston Building Inspection Office or any emergency concerns will be addressed and pricing may need to change accordingly.Any amendments requested by the City of Houston Building Inspection Office or any emergency concerns will be addressed and pricing may need to change accordingly." %>
      <% else %>
      <%= print "." %>
      <% end %>

      <div id="terms">
        <textarea>Enter addtional job description</textarea>
      </div>
</section>

    </div>
  <table id="items">

    <tr id="hiderow">
      <td colspan="5"><a id="addrow" href="javascript:;" title="Add a row"></a></td>
    </tr>

    <tr>
      <td colspan="2" class="blank"> </td>
      <td colspan="2" class="total-line">Sales Tax</td>
      <td class="total-value"><div id="subtotal">$875.00</div></td>
    </tr>
    <tr>

      <td colspan="2" class="blank"> </td>
      <td colspan="2" class="total-line">Total</td>
      <td class="total-value"><div id="total">$875.00</div></td>
    </tr>
    <tr>
      <td colspan="2" class="blank"> </td>
      <td colspan="2" class="total-line">Amount Paid</td>

      <td class="total-value"><textarea id="paid">$0.00</textarea></td>
    </tr>
    <tr>
      <td colspan="2" class="blank"> </td>
      <td colspan="2" class="total-line balance">Balance Due</td>
      <td class="total-value balance"><div class="due">$875.00</div></td>
    </tr>

  </table>

  <div id="terms">
    <h5>Terms</h5>
    <textarea>Any amendments requested by the City of Houston Building Inspection Office or any emergency concerns will be addressed and pricing may need to change accordingly.</textarea>
  </div>

  <p>
    </br></br></br>
    <table>
    <tr>
      <td>
    ____________________________________________
      </td>
      <td>
    __________
      </td>
    </tr>
    <tr>
      <td>
    Customer Signature
      </td>
      <td>
    Date
      </td>
    </tr>
    <tr>
    <td>
    ____________________________________________
    </td>
    <td>
    __________
    </td>
    </tr>
    <tr>
    <td>
    Burt Koenig
    </td>
    <td>
    Date
    </td>
    </tr>
    </table>
  </p>

</div>



</body>

</html>

<%= link_to 'Edit', edit_bid_sheet_path(@bid_sheet) %> |
<%= link_to 'Back', bid_sheets_path %>